### PR TITLE
Please merge series of minor improvements

### PR DESCRIPTION
**Pull request by paulvanharen**
Dear Adrian,

I'm keeping on developing my Robot Framework test scripts, meanwhile making minor improvements to the SukulixLibrary. I'd like to share my latest changes with you.

- The biggest change is that I've added a parameter to specify how to define a region to all find methods. The former method is still in place and the changes are backwards compatible.
- I've created a small Debug class, to interface to the SikuliX Debug class. It is now possible to manage the SikuliX logging and debug output.
- The hardcoded screen dimensions (1920x1080) are now replaced by calls to the SikuliXLibrary. This now also supports my 3840x1440 screen ;)
- I've added keywords to get text, and to make and log screenshots.
- I've changed all camelCase keywords into underscored keywords. The result is that libdoc will now generate keyword names containing spaces (improved readability), meanwhile staying backwards compatible.
- I've made various documentation improvements.

I hope that you can appreciate these changes.

Best regards, Paul

### CODE REVIEW

**Review by adrian-evo — CHANGES_REQUESTED** [review]
The library should work also with Python (i.e. outside Robot Framework), thus changing method name is not backward compatible. If underscore name is important (but I guess not), one option would be to have duplicate method with both old and new names, otherwise please keep the old name.

**Review by adrian-evo — CHANGES_REQUESTED** [review]
The library should work also with Python (i.e. outside Robot Framework), thus changing method name is not backward compatible. If underscore name is important (but I guess not), one option would be to have duplicate method with both old and new names, otherwise please keep the old name.

**Review by adrian-evo — CHANGES_REQUESTED** [review]
The library should work also with Python (i.e. outside Robot Framework), thus changing method name is not backward compatible. If underscore name is important (but I guess not), one option would be to have duplicate method with both old and new names, otherwise please keep the old name.

**Comment by adrian-evo** [comment]
Hi Paul,

Thanks for your work on library improvements. I hope it is very useful for your testing scripts. However, besides the above requested changes, I would recommend that you also run locally the tests specified under Testing readme section, without modifying them, so that they are backward compatible. for both Python and Robot Framework. Additionally, you can extend the tests or write new ones as needed, so that we are calling each implemented method or keyword at least once, and ensure it works as expected.


Best regards,
Adrian

**Comment by paulvanharen** [comment]
Hi Adrian,

Thank you for your explanation. I'll follow up and make necessary modifications (and tests) later this week.

Best regards, Paul

**Comment by paulvanharen** [comment]
Dear Adrian,

I've reworked the all method names to be the same as these used to be. Using the SikuliXLibrary has no longer issues in combination with Python. 
I also looked at the tests in the same archive and I'm able to run all tests on by Ubuntu machine. However, I don't know how to judge the test results and I would appreciate your feedback testing the current version on other platforms.

We could discuss using PyTest for running the test cases, and rework the existing test cases accordingly. Please advise.

Best regards, Paul

**Comment by adrian-evo** [comment]
Hi Paul,

I checked carefully and tested the proposed changes, however, still there are some issues to be fixed. Hope you will not give up but rather investigate further. :)

1. While your changes might work fine with JPype in your environment, unfortunately some of these will not work with Py4J (which some people might use instead), for example:
- sikulixregion.py: getBottomRigh() return a Location object in Py4J and thus it cannot be used to call br.x, br.y. What seems to work is x = self.appScreen.getW(), getH() instead.
- Using JInt, JFloat, JDouble, JBoolean is not recognised by Py4J unfortunately. I am not sure what would be the solution, maybe you can investigate further. This means also previous pull request with using JFloat is not working with Py4J (not tested at that time). If no solution can be found and only JFloat is important for you, then you can handle this particular case for JPype only for example.

If you can test with Ubuntu for both JPype and Py4J that woud be fine, I can test later with Windows and MacOS.

2. set_notFoundLlogImages - small typo on line 58 on sikulixlogger.py


Best regards,
Adrian

**Comment by paulvanharen** [comment]
Hi Adrian, 

Thank you for your patience. In the PY4J gateway, there is this setting `auto_field` which enables access to class members, similar as in Jpype. Enabling that switch cured most of the problems. 

Of course, there still is the issue with the type conversion. AFAIK, only the Java float type has no equivalent in Python; Python only uses doubles. All other used types have a one-to-one correspondent in Java. Therefore, I choose to implement most of the required type conversion on the Python side; only converting doubles to floats takes place on the Java side. It all takes about 10 lines of code, which are stored in the new `sikulixpy4j.py` file.

The tests using JPype and PY4J produce similar results now. Please double check the tests, as I'm not yet 100% confident that everything is perfect now. 

Best regards, Paul

**Comment by adrian-evo** [comment]
Hi Paul,

I tested carefully (hopefully) the chances and except for a maybe minor change that I will correct before making a new release, it should work now. The issue is that although the testing pass on Windows and as you said also on Linux, still what is not working on MacOS with py4j is the method getBottomRigh() as I mentioned above. But replacing it with getW() and getH() instead seems to work, so I suppose we can keep it like this for now.

Best regards,
Adrian

**Pull request merged**
